npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: false
nodeLinker: node-modules

npmScopes:
  variablesoftware:
    npmAlwaysAuth: false
#    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
